[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"

[mcp_servers.context7.headers]
CONTEXT7_API_KEY = "ctx7sk-d20f3c8b-a40a-4de5-a8ad-c383408a8031"

[mcp_servers.packages-api]
url = "http://localhost:3355/api/mcp"

[mcp_servers.playwright]
args = ["@playwright/mcp@latest"]
command = "npx"

[mcp_servers.braingrid]
command = "npx"
args = ["-y", "mcp-remote@latest", "https://mcp.braingrid.ai/mcp"]

